### ISSUE TITLE
Research JavaScript Frameworks

### ISSUE THREAD

**Issue by MKELEGOGuy** [KenoshaLUG/LUGServicesWebClient#1]
Research and compare the following JavaScript Frameworks:
- AngularJS
- Backbone.js
- DHTMLX
- Dojo
- Ember.js
- Enyo
- Knockout
- MooTools
- React
- Prototype
- SproutCore
- Unified.js
- Vue.js
- Webix

Key considerations are:
- Price
- Licensing
- Ease of use
- RESTful Web API Support

**Comment by MKEDataGuy** [comment]
I went through and weeded out all the frameworks which don't offer free versions.

**Comment by Jameson42** [comment]
Picking [Angular](https://angular.io/) due to the breadth of documentation and examples available, and its focus on working with data.  It looks the easiest to work with of the available frameworks as well. 

We'll still need to either build our own CSS or start from something like Bootstrap, Foundation, Skeleton, etc. I'll open a separate task for CSS framework selection.
